### ISSUE TITLE
The default eventOrOptions argument in the publish() method should be 'message'

### ISSUE THREAD

**Issue by andrewyang96** [schwarzkopfb/sse-broadcast#1]
The EventSource `onmessage` event handler won't fire unless the received message's event type is `message`. Your Express demo is a little misleading in that regard if someone just wants to connect an EventSource object on the frontend to an sse-broadcast powered endpoint. Otherwise, this is a great Node package! It's much better than the one I tried building :smiley:

**Comment by schwarzkopfb** [comment]
Thank you for your feedback and kind words!

I tried to reproduce the problem you mentioned using [this](https://gist.github.com/schwarzkopfb/1459da5b86a9fbc02725cd8f78c670c0), but it seems to work as intended in all the up-to-date versions of popular browsers.

Moreover, [this](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) article says that the `event` field in SSE messages is optional (see the `Examples/Data-only messages` section).

So, I'm not sure about the real issue here, so please provide some more information (e.g. browser, browser version, node version, os, sample code, etc.) about your use-case. Thanks!

**Comment by andrewyang96** [comment]
My environment is Windows 10, Node v4.5.0, and the latest versions of Chrome (52.0.2743.116) and Firefox (48.0.2). My sample code is located in this repository: https://github.com/andrewyang96/nodejs-sse-example

The SSE messages arrive successfully to the browser, but whatever function I attach to EventSource's `onmessage ` attribute does not fire when these messages arrive at the browser.

**Comment by schwarzkopfb** [comment]
According to Mozilla's [docs](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events):

> [The `onmessage` handler] listens for incoming messages (that is, notices from the server that **do not have** an `event` field on them) [...]

In the previous version of your code, you tried to send `update` events, thus messages did **have** an `event` field:
```
event: update
data: random number or uuid
```

So, in compliance with the docs, the browser's expected behaviour is to **not** fire the `onmessage` handler. 

If you're using named events, you should use the `addEventListener()` method:
```js
new EventSource('/events').addEventListener('update', function(e) { /* work your magic */ })
```

`onmessage` is for _data-only_ messages:
```
: no event field here
data: random number or uuid
```
```js
new EventSource('/events').onmessage = function(e) { /* do awesome things */ }
```

I [forked](https://github.com/schwarzkopfb/nodejs-sse-example/commit/4d9385e1f6ec75863eee32e0632b8258b87fcbd0) your repo to show these in place.

Setting the default event to `message` assumes that the `event` field is always added to messages. Consequently the user would not be able to send data-only messages and that's too opinionated. Therefore I'm not going to change that default value, sorry. 🙁

However, your problem is solved and - hopefully - this experience may be useful later! 😉 
Is there something else I can help with?

**Comment by andrewyang96** [comment]
Ah, I see. Thanks for the clarification!

**Comment by Globik** [comment]
Data messages with no event are useful for 'ping'. Where on heroku for example any sse stream is dying after 50 secs.
